### ISSUE TITLE
Refactoring: exception handling

### ISSUE THREAD

**Issue by freerouting** [freerouting/freerouting#1]
Exception handling needs to be improved.

The worst example currently in the code base would be:
        } catch (Exception e)
        {
        }

Yes, just "catch any exception and totally ignore it". That's wrong.

First of all, there are very little cases when you should be catching general 'Exception' - it should be more specific what exactly you are catching and why.

```
        try
        {
            result = this.file_contents.getInputStream();
        } catch (Exception e)
        {
            result = null;
        }
```

Should probably be IOException?

Another issue - with a Swing GUI users do not see the console by default, so writing to stdout is not best useability. Actually, most of the runtimes - the unexpected exceptions - should be taken care by a global exception handling FRAME, probably alongside with writing to a log.

**Comment by andrasfuchs** [comment]
I agree. I started to do the refactoring, but it's not complete yet.

You can get the version where logging is done by log4j and Exception are logged as errors with details from this repo: https://github.com/miho/freerouting
