### ISSUE TITLE
FreeRouting command line argument for Win32 jar file doesn't work -oit 0

### ISSUE THREAD

**Issue by lynchaj** [freerouting/freerouting#102]
First of all, thank you for taking the time to report an issue.

To make our work easier, please provide as many details as you can:
* [ ] What version of freerouting are you using? 1.5.0
* [ ] On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit? Win32, using jar file to OpenJDK
* [ ] What type of file are you working with? Can you attach the actual (DSN) file? DSN file
* [ ] Did you use any command line arguments? Yes, -oit 0, shortcut properties target says ""C:\Users\Andrew\Desktop\System CD Updates\applications\freerouting-1.5.0.jar" -oit 0"
* [ ] Can you post a screenshot of the problem?
* [ ] Can you include the latest, related log entries from the .log file?
* [ ] Please list the detailed steps to reproduce the problem
* [ ] What would you expect freerouting to do in this situation? honor command line arguments and run until no more routes
* [ ] Is fixing this issue critical for your work? No, but distracting and causes additional work

It appears for the Win32 FreeRouting jar file it does not accept command line arguments or at least they are not working like I would expect them to.  Maybe I am doing this wrong?

My intent is to override the default FreeRouting behavior so it runs until no routes left to test:

"-oit [percentage]: stops the route optimizer if the improvement drops below a certain percentage threshold per pass. Default is 0.1%, and 0% means to continue improving until there are no more route options to test."

Present behavior is that FreeRouting stops after about an hour or two when there are still routes to test.  Running same DSN under FreeRouting 1.2.43 extra the trace route optimization would normally continue for days or weeks testing routes

My suggestion: Duplicate the command line arguments in the menu as selectable parameters.  There are bunch there already so this would be an extension of present menu system by adding a page for the command line arguments

I hope this helps.  Thanks, Andrew Lynch

**Comment by andrasfuchs** [comment]
Hey Andrew,

Thank you Andrew again for the fine suggestion, I appreciate it!

I made a few modifications to the `-oit` parameter, so now if you now start freerouting with `-oit 0` it should go indefinitely until you manually stop it. The default setting is now 0.25%, but I'm open to change it something more practical.

Could you make a few tests with different values, let's say between 0.1 and 0.0000001, and 0, and let me know what worked best for you?

Please make sure that you [the latest snapshot build](https://github.com/freerouting/freerouting/releases/tag/SNAPSHOT).
