### ISSUE TITLE
my .dsn file is stuck on loading design

### ISSUE THREAD

**Issue by bradac1** [freerouting/freerouting#106]
First of all, thank you for taking the time to report an issue.

To make our work easier, please provide as many details as you can:
* [x] What version of freerouting are you using?
* [x] On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?
* [x] What type of file are you working with? Can you attach the actual (DSN) file?
* [ ] Did you use any command line arguments?
* [x] Can you post a screenshot of the problem?
* [ ] Can you include the latest, related log entries from the .log file?
* [ ] Please list the detailed steps to reproduce the problem
* [ ] What would you expect freerouting to do in this situation?
* [x] Is fixing this issue critical for your work?

**Comment by bradac1** [comment]
Im using th 64-bit version. I just downloaded it so its the latest version.
![Screenshot 2022-03-10 184959](https://user-images.githubusercontent.com/101355325/157724439-b0ca3c48-c0f6-4628-84d9-6d19b6b33040.png)

**Comment by andrasfuchs** [comment]
Could you attach the DNS file you tried to load?

Do you have the log file by any chance?
