### ISSUE TITLE
 freerouting does not find obvious rutes?

### ISSUE THREAD

**Issue by githubaf** [freerouting/freerouting#107]
I am using "INFO  Freerouting v1.5.0 (build-date: 2022-01-27)" under ubuntu 20.04.3 LTS (running in Virtualbox)
In Windows Kicad 5.1.5-3 Windows7 64  I created a pcb and exported a dsn file. In Linux I run freerouting "java -jar freerouting-1.5.0.jar"
I select the dsn file to open. Then in Parameter/Autoroute I deselect F.Cu to get a single layer PCB.
Then Autoroute.
After 2...4 Minutes routing is complete and optimization starts, After another 4 minutes the optimizer is ready. Nice!

Now, back in Kicad I added 2 BNC-Connectors to the PCB and exported it again as dsn File. If I now autoroute the new dsn-File, the autorouter will never finish.

The autorouter would have to create only 4 more tracks and that are very simple tracks. If I import the first (completeley routed ses-File without these two connectors) back into PCBNew I can add the two components there manually and add the new tracks easily manually with the interactive router of PCBnew.
Why can freerouting not route the complete board? Do I have a misunderstanding here? Do I have to alter any parameters?
I could live with the manual step but I wonder if there is bug in freerouting or if I did not use it correctly.

Please find the two dsn-files in the archive attached. Both files only differ in these two additional connectors.
Thank you very much for your work!

[freq_teiler_200kHz_kicad.zip](https://github.com/freerouting/freerouting/files/8309776/freq_teiler_200kHz_kicad.zip)

**Comment by erichVK5** [comment]
Is there a reason you are constraining the autorouting to one layer?

Some of the traces generated are quite tortuous with single layer routing attempts. Single layer routing is not always possible topologically.

The board routes quite well as a two layer board.

You may wish to try a simpler test case to see if there is an issue with KiCad exporting a partially autorouted layout, thereby ruling out an issue with the DSN being exported.

**Comment by githubaf** [comment]
> Is there a reason you are constraining the autorouting to one layer?
Yes, the producer with the best price doesn't do vias and single side is cheaper than double sided.

> Single layer routing is not always possible topologically.
That is absolutely clear. My point was:
- the first dsn-file I showd can be roueted completely in freeroute.
- The second one only adds two connectors. If I take the result from the first routing and add the two connectors manually, I can very easily add the additional traces manually. (That is a have done actually) So it should be topographically possible to autoroute the complete board, shouldn't it?

One additional thing I observed:
During my work I found a routable layout (without the two connectors) Then I changed the placement of the components a tiny bit, such as shifting only one IC a centimeter to the right. There is still enough space between all pads the find the same traces again, but freerouting cannot solve the puzzle again...

**Comment by andrasfuchs** [comment]
I haven't tested it yet, but I think you are right @githubaf ,this should not be a problem for freerouting and it's very likely a bug. Thank you for reporting and for the sample files.

**Comment by andrasfuchs** [comment]
@githubaf , I have just tested your files with the newest snapshot build.

The first file (freq_teiler_200kHz_kicad.dsn) with its .rules was completed in a few minutes with one unroutable connection. 
The second file (freq_teiler_200kHz_kicad_bad.dsn) without the .rules completed fully as far as I can tell. If I applied the same rules to it, it also finished with one unroutable connection.

Could you also [download the snapshot build](https://github.com/freerouting/freerouting/releases/tag/SNAPSHOT), and test it if it works as you would expect?
