### ISSUE TITLE
Excessive GPU usage for window drawing

### ISSUE THREAD

**Issue by tehKaiN** [freerouting/freerouting#113]
First of all, thank you for taking the time to report an issue.

To make our work easier, please provide as many details as you can:
* What version of freerouting are you using? **1.5**
* On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit? **Windows x64**
* What type of file are you working with? Can you attach the actual (DSN) file? [Protein.zip](https://github.com/freerouting/freerouting/files/8818655/Protein.zip)
* Did you use any command line arguments? **No**
* Can you post a screenshot of the problem?

![big_size](https://user-images.githubusercontent.com/16180344/171499054-98a73c81-2781-457d-a879-4bcbd01776e3.png)

![small_size](https://user-images.githubusercontent.com/16180344/171499089-f2a56cc1-b50b-4ff0-8de1-86a76c9517b6.png)

* Can you include the latest, related log entries from the .log file? **not applicable**
* Please list the detailed steps to reproduce the problem
  * Run the solver
  * Set the window size to large one
  * Observe extensive usage of GPU
  * Resize the window to smaller one
  * Observe significantly smaller GPU usage

Problem persists when application is out of focus (e.g. alt-tabbed to different window) but is solved by minimizing the window.

* What would you expect freerouting to do in this situation?
  * Reduce the refresh rate when window is out of focus
  * Preferably optimize board drawing so that it doesn't do full 60fps or whatever the cap is but make use of OS redraw/dirty events and/or redraw only when board state is updated

* Is fixing this issue critical for your work? **It's nice to have**

**Comment by andrasfuchs** [comment]
Thank you for reporting! 
You are right, the routing and the GUI updates should be running on different threads and the number of updates to the GUI should be capped.
