### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by EasyEDA2021** [freerouting/freerouting#130]
this is EasyEDA Pro auto route logo(icon), we would like to offer it to freerouting as logo, if freerouting needs

![eda-routing-auto](https://user-images.githubusercontent.com/29702100/178998131-b5b3743e-8f52-4e61-8922-cb4213ff752c.svg)

for example
![图片](https://user-images.githubusercontent.com/29702100/178998827-4bb1207d-fa66-4b5a-9991-f8dd59e0bf66.png)

**Comment by EasyEDA2021** [comment]
[eda-routing-auto.zip](https://github.com/freerouting/freerouting/files/9112400/eda-routing-auto.zip)

**Comment by andrasfuchs** [comment]
Thank you, that's very kind of you!

I'll save the file for later use, hopefully we will have a volunteer UI/UX designer in the future :)
