### ISSUE TITLE
Freerouting as Python package

### ISSUE THREAD

**Issue by joamatab** [freerouting/freerouting#132]
How could we add a python API for freerouting?

it would be great to interface with different tools such as gdsfactory [routers](https://gdsfactory.github.io/gdsfactory/routing.html)

@miho 
@proppy

**Comment by andrasfuchs** [comment]
If I understand it correctly you would prefer to have a Python API interface for freerouting, so I'm not sure it helps, but our KiCad integration is done by using Python. You can see the source [here](https://github.com/freerouting/freerouting/tree/master/integrations/KiCad).

**Comment by joamatab** [comment]
nice,

ideally we upload it to [PyPi](https://pypi.org) so we can `pip install freerouting`

**Comment by andrasfuchs** [comment]
I'm not a Python expert at all, but I image that we would first need to refactor Freerouting to have a separate Java library that have an API that can be called from Python (probably with the help of [Py4J](https://www.py4j.org/index.html)). 
If that worked we could add it as a package to pip with [PyPi](https://pypi.org/).

It doesn't look impossible, but it would be a lot of effort with our current software architecture.

**Comment by andrasfuchs** [comment]
@abelom Could you also give me repo creation rights as well? I think it would be not too much effort to create separate client libraries in different languages in the future, and they would need new repos each.

**Comment by abelom** [comment]
@andrasfuchs just changed your role to 'owner', please validate.
