### ISSUE TITLE
How to get via location?

### ISSUE THREAD

**Issue by mayidu** [freerouting/freerouting#136]
First of all, thank you for taking the time to report an issue.

To make our work easier, please provide as many details as you can:
* [ ] What version of freerouting are you using?
* [ ] 1.6.2
* [ ] On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?
* [ ] Windows
* [ ] What type of file are you working with? Can you attach the actual (DSN) file?
* [ ] DSN
* [ ] Did you use any command line arguments?
* [ ] NO
* [ ] Can you post a screenshot of the problem?
* [ ] yes
* [ ] Can you include the latest, related log entries from the .log file?
* [ ] no
* [ ] Please list the detailed steps to reproduce the problem
* [ ] What would you expect freerouting to do in this situation?
* [ ] Is fixing this issue critical for your work?

Hi, Mr.
   I used the freerouting to auto-routing a large PCB board, but I find there are some problems！
eg: 1、Internal traces of the component！
![image](https://user-images.githubusercontent.com/29938271/186602153-c15f7e2c-0ea3-40eb-853f-ef10faa5bd86.png)
2、How is the wiring sequence determined? I've found that there are some obvious things that can be routed, but can't actually be routed！
![image](https://user-images.githubusercontent.com/29938271/186604110-76ce6c4c-b543-4f6c-9c4f-f3ac5eb1ad24.png)

3、I would like to know how the via is determined in auto-routing！your code is java, but I'm good at python， I don't understand your code, can you tell me the idea, thanks！

**Comment by andrasfuchs** [comment]
Hello @mayidu, 

Could you send me sample files and the reproduction steps so that I can see the problem locally?

Thank you!
