### ISSUE TITLE
Window to open file is missing button

### ISSUE THREAD

**Issue by denjhang** [freerouting/freerouting#150]
![sshot-20221018-200156](https://user-images.githubusercontent.com/61811583/196582385-259f6817-fc72-4563-b3b5-d1658e56773f.png)
![sshot-20221019-102146](https://user-images.githubusercontent.com/61811583/196582401-cbea880e-e61a-461d-9bad-78767110ec88.png)
![sshot-20221019-102658](https://user-images.githubusercontent.com/61811583/196582789-c795a646-aaea-4a7b-9732-9194a6033186.png)

I'm currently using freerouting v1.6.2, and I found that when I first opened the program, I clicked "Open Your Design" and the file selection window popped up. But the "Open" button in the bottom right corner of the file selection window disappears around 0.5s. After I turned it off and clicked "Open Your Design" again, the "Open" button returned to normal.

**Comment by denjhang** [comment]
![sshot-20221018-200156 - 副本](https://user-images.githubusercontent.com/61811583/196582981-1b91a066-8a1d-42fe-b363-581dfae57e58.png)

**Comment by andrasfuchs** [comment]
It's strange, can this be a window sizing issue? The window on the last screenshot is narrower than the others above.

As I tried to reproduce this issue, I could resize my window to a too small size:
![image](https://user-images.githubusercontent.com/910321/196891072-e9590529-610d-409a-84de-4b05f7ca0498.png)

You can fix this by moving the mouse cursor to the bottom right corner of the window and resize it.

The fix should be that a minimum width and height must be set to this (and I think all other) windows.

**Comment by denjhang** [comment]
Although I adjusted the window to temporarily solve the problem, the enter key did not work. When I close the window and open it for the second time, everything works fine.

**Comment by andrasfuchs** [comment]
It got fixed in version 1.7.0, so I close this now.
