### ISSUE TITLE
Incorrect application and window icons

### ISSUE THREAD

**Issue by EasyEDA2021** [freerouting/freerouting#161]
not a important issue
![图片](https://user-images.githubusercontent.com/29702100/212261833-27dfc268-c7e1-45cf-8297-783826d09372.png)
the icon not freerouting icon, it shows java icon

the open dialog is correct
![图片](https://user-images.githubusercontent.com/29702100/212262090-a225a1aa-a440-4589-b4e3-9dcc2396e336.png)

but the other dialogs are not correct
![图片](https://user-images.githubusercontent.com/29702100/212262306-8bccf78a-3791-4bc5-89b7-05691e6f3509.png)

**Comment by andrasfuchs** [comment]
It got fixed in version 1.7.0, so I close this now.

**Comment by EasyEDA2021** [comment]
> It got fixed in version 1.7.0, so I close this now.

hi，I tested it, still have windows no icon, the task bar no icon too
![图片](https://user-images.githubusercontent.com/29702100/219354970-2c801a15-899b-485e-8337-258056c88e0b.png)
![图片](https://user-images.githubusercontent.com/29702100/219355035-547b3e85-164c-497b-871b-1c9e4c8c27f7.png)
![图片](https://user-images.githubusercontent.com/29702100/219355345-5b46334d-4095-49c9-b68d-5b8b2ea57f23.png)
![图片](https://user-images.githubusercontent.com/29702100/219355614-3cb0399a-4e00-48ad-a0f3-5f5d94f40adc.png)

maybe it was because of overiding old version to install new version(old version cache) ?

**Comment by andrasfuchs** [comment]
Ah, you are right, I replaced the icon on the windows, but not for the application itself.

Thanks, I'll reopen this, and try to fix next time.

**Comment by andrasfuchs** [comment]
It will be fixed in the next release.

![image](https://user-images.githubusercontent.com/910321/236232029-a00cab31-221b-4919-bb95-51aeb927fe71.png)
