### ISSUE TITLE
Release files usability

### ISSUE THREAD

**Issue by rusefi** [freerouting/freerouting#17]
Typically an end-users of any tool has to download one most important for end user file.

In our case we have freerouting.exe and what else? Which jar(s)? I would suggest packaging all the files needed to the end user into one .zip for a release.

To be honest I am a java developer yet I had to google the difference between freerouting.jar and freerouting-executable.jar myself - that's a gradle naming convention for "-with-dependencies" vs "-no-dependencies".

What is the workflow to create freerouting.exe since we no longer have it in repository?

**Comment by miho** [comment]
**Update:** there are native packages for all major platforms. They are built via GitHub Actions and uploaded automatically whenever a release is created on GitHub. The freerouting-executable.jar is now merely a fallback for platforms/architectures we don't support officially.

**Comment by miho** [comment]
snapshots are provided in a "SNAPSHOT" release: https://github.com/miho/freerouting/releases/tag/SNAPSHOT

**Comment by rusefi** [comment]
https://github.com/miho/freerouting has great usability, this issue is closed
