### ISSUE TITLE
KiCad 7.0 Error "Board may be corrupted"

### ISSUE THREAD

**Issue by Devilscave** [freerouting/freerouting#175]
To make our work easier, please provide as many details as you can:
* [ 1.7.0 ] What version of freerouting are you using?
* [ Win 11 ] On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?
* [ KiCad ] What EDA do you use? KiCad, EAGLE, other?
* [ Project ] What type of file are you working with? Can you attach the project files (.pro, .kicad_pcb, etc) or the exported DSN file?
* [ NO ] Did you use any command line arguments?
* [ yes ] Can you post a screenshot of the problem?
* [ ] Can you include the latest, related log entries from the .log file?
* [ ] Please list the detailed steps to reproduce the problem
* [ routing ] What would you expect freerouting to do in this situation?
* [ NO ] Is fixing this issue critical for your work?

Hello, i have a BUG mit KiCad 7.0 and freerouting 1.7.0 (Java 17 used)
The problem occurs when I have put all the parts in your position in the circuit board editor and activate the autorout.
The plugin starts and also begins to put a few lanes. Then it closes completely and the message comes in Kicad:
`ERROR`
`Board may be corrupted, do not save it.`
`Fix problem and try again`
`Expecting 'component_id' in 'G:/KiCad/7.0/Projects/test2/freerouting.ses', `
`line 13, offset 14.`

After confirming the error:
`KiCad Freerouting Plugin`
`Failed to invoke:`
`* pcbnew.ImportSpecctraSES`

I tried the standalone version of freerouting and opened the Freerouting.dsn file and it worked. I could also save it, but then I try to import it into Kicad comes the same Error again. So I once looked into the file with Notepad ++ and went into the specified line.
12    `(component "Package_SO:SOIC-16_3.9x9.9mm_P1.27mm"`
13    `(place 2003 1043250 -1104250 front 270)`
14    `)`

I don't know exactly what it is, I find line 13 but what value is offset 14?!?! The component on which reference is made is an ULN2003 transistor array. Freerouting runs through and also puts my routes nice but he can probably not transmit it. Or Kicad has problems with the component. But it is quite normal from the list like everyone else.

**Comment by andrasfuchs** [comment]
Thank you for the clarification and investigation! I'm glad it worked in the end.
