### ISSUE TITLE
KiCad plugin: can't load DSN, but no errors or warnings are shown

### ISSUE THREAD

**Issue by benirieth** [freerouting/freerouting#181]
To make our work easier, please provide as many details as you can:
* [x] What version of freerouting are you using?
* [x] On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?
* [x] What EDA do you use? KiCad, EAGLE, other?
* [x] What type of file are you working with? Can you attach the project files (.pro, .kicad_pcb, etc) or the exported DSN file?
* [x] Did you use any command line arguments?
* [x] Can you post a screenshot of the problem?
* [x] Can you include the latest, related log entries from the .log file?
* [x] Please list the detailed steps to reproduce the problem
* [x] What would you expect freerouting to do in this situation?
* [x] Is fixing this issue critical for your work?

**Comment by benirieth** [comment]
Im using the latest version of kiCAD and freerouting as well. 20230301
Windows 10 x64
its a dsn file
i didnt use any command line arguements
I tried to open an other file. That could handle it. It contain a bit more parts 155x95 mm the PCB size, approx 100 components

**Comment by andrasfuchs** [comment]
Thanks @benirieth for the report. 

I can't help you without the KiCad project files or the DSN file. Could you provide them you so that I can look into this?

I've just made a few fixes to our snapshot build, so alternatively you could try to open the file with that.
