### ISSUE TITLE
New version of freerouting don't work with Kicad 7.0. Standalone version works only with files made by Kicad 6.0.

### ISSUE THREAD

**Issue by jwolbink** [freerouting/freerouting#192]
The new version of Freerouting don't work with Kicad 7.0. Standalone version works only with files made by Kicad 6.0.It all runs on Linux Mint (new version) . I'm a older hobbyist (68) and a hope someone can help me with this problem. I have also installed the latest version of Java 17.0 JDK.

**Comment by retiredfeline** [comment]
I think this is due to issues with KiCad v7 DSN generation mentioned here #185 It may be fixed in the upcoming v7.0.4. If you'd like to help you could try using the KiCad testing build which is pre-v7.0.4.
