### ISSUE TITLE
HOWTO use CodeSee Maps?

### ISSUE THREAD

**Issue by abelom** [freerouting/freerouting#196]
just attempted installing CodeSee Maps

Did it go right?

Where does one see any results/features/consequences?

**Comment by andrasfuchs** [comment]
It looks good, but I need to learn more about it to make it useful. Do you have any experience with it?

![image](https://github.com/freerouting/freerouting/assets/910321/d98cec38-7eb3-4d01-8a3c-406b4cdf5945)

I hope it helps with the refactoring effort that would be needed for [the headless CLI version](https://github.com/freerouting/freerouting/discussions/195).

**Comment by andrasfuchs** [comment]
CodeSee didn't work out in the end, Shanea Leven, the founder couldn't resolve our technical issue.

I don't seem to have the right to remove its access to the repo, @abelom could you take a look?
https://github.com/apps/codesee-maps/installations/37536226

**Comment by abelom** [comment]
``You're all set. A job has been queued to uninstall CodeSee Maps  ``
