### ISSUE TITLE
I can't change the width of the slopes

### ISSUE THREAD

**Issue by Betureee** [freerouting/freerouting#198]
I'm working on a pcb and I installed the latest version of the autorouting tool on KiCAD 6.0, the problem is that when I click to open the autorouting window does 1 or 2 seconds of loading and starts immediately to do the autorouting, so I can not change the measurements of tracks and routes, the problem is that if I change it once the routing is finished the tracks are short of each other, basically I can not change any setting, when the tool does everything with default options, in my opinion another very inconvenient thing is to click with the left mouse button to stop the tool, it would be more convenient that the autorouting window opened and there are all the options for routing, and then be able to start or stop it from the menu bar, could you tell me how I can do to change the width of the tracks before autorouting, I hope these tips can help improve the tool :)

<sup>Originally posted by **Betureee** May 21, 2023</sup>
`Sto lavorando ad un pcb e ho installato l'ultima versione del tool dell'autorouting su KiCAD 6.0, il problema è che quando clicco per aprire la finestra di autorouting fa 1 o 2 secondi di caricamento e parte subito a fare l'autorouting, così non posso cambiare le misure di piste e vie, il problema è che se lo cambio una volta finito il routing le piste fanno corto tra loro, in sostanza non posso cambiare nessuna impostazione, quando parte il tool fa tutto con opzioni di default, secondo me un altra cosa molto scomoda è cliccare con il tasto sinistro del mouse per stoppare il tool, sarebbe più comodo che si aprisse la finestra di autorouting e ci siano tutte le opzioni per il routing, e poi poterlo avviare o stoppare dalla barra dei menù, sapreste dirmi come posso fare per cambiare la larghezza delle piste prima dell'autorouting, spero che questi consigli possano aiutare a migliorare il tool:)`

**Comment by andrasfuchs** [comment]
Thank you for the feedback!

You will have the option to change the settings before the auto-router starts in the next release.
