### ISSUE TITLE
Refactoring: logging

### ISSUE THREAD

**Issue by freerouting** [freerouting/freerouting#2]
Currently the code writes to standard console

```
        System.out.print("AutorouteEngine.complete_expansion_room: ");
        System.out.println(e);
```

First of all users do not have access to stdout by default, second this should be written to a file so that further troubleshooting could be possible, this should also be encapsulated.

Looks like there is already a class related to logging - it should be used wider.

**Comment by andrasfuchs** [comment]
I refactored the logging of freerouter, so now it uses the fully customizable log4j as its logging framework.

You can check it out here: https://github.com/miho/freerouting
