### ISSUE TITLE
Windows dpi scaling goes wrong

### ISSUE THREAD

**Issue by markuckermann** [freerouting/freerouting#20]
I hope this is the correct repo for issues!

After starting freerouter it looks normal but as soon as I click on "Open your own desgin", everything is twice the size it should be. Possibly something to do with having a 4k high dpi screen but the same thing happens on my second screen (1080p). 

![image](https://user-images.githubusercontent.com/17556569/77441346-3e638480-6de1-11ea-83de-ba98b2b3710e.png)

After clicking: 
![image](https://user-images.githubusercontent.com/17556569/77441796-be89ea00-6de1-11ea-87b8-2ff72163f555.png)

This leaves a lot of text invisble or hard to read: 

![image](https://user-images.githubusercontent.com/17556569/77441894-e37e5d00-6de1-11ea-95d5-0a9c30d3db1c.png)

Cheers to all who keep working on this!

**Comment by markuckermann** [comment]
**Workaround** 

If you specify the .dsn file via the command line it works well.
`\AppData\Local\Freerouting\Freerouting.exe -de '.\path_to\file.dsn'` 

This opens the dsn file immediately and the scaling issue doesn't appear.

**Comment by andrasfuchs** [comment]
Thank you @markuckermann for reporting this!

Could you share your Windows _Scale and layout_ settings with us?

![image](https://user-images.githubusercontent.com/910321/77453065-08c99600-6df7-11ea-9e06-5522f27076d6.png)

Do you have anything set in the _Advanced scaling settings_?

![image](https://user-images.githubusercontent.com/910321/77453201-3ca4bb80-6df7-11ea-8599-3770dc23f904.png)

**Comment by markuckermann** [comment]
@andrasfuchs yes I can:
![image](https://user-images.githubusercontent.com/17556569/77655040-c6749600-6f69-11ea-8f99-8548672430c1.png)
