### ISSUE TITLE
autoroute finishes only with a bigger boundary

### ISSUE THREAD

**Issue by choas** [freerouting/freerouting#209]
To make our work easier, please provide as many details as you can:
* [ ] What version of freerouting are you using? 1.8.0
* [ ] On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit? macOS 64-bit
* [ ] What EDA do you use? KiCad, EAGLE, other? KiCad 7.0.5-0
* [ ] What type of file are you working with? Can you attach the project files (.pro, .kicad_pcb, etc) or the exported DSN file? DSN files exported from KiCad
* [ ] Did you use any command line arguments? `java -jar freerouting-1.8.0.jar`
* [ ] Can you post a screenshot of the problem? no
* [ ] Can you include the latest, related log entries from the .log file? no
* [ ] Please list the detailed steps to reproduce the problem
  - generate two different KiCad pcb file with ergogen; one (split10) with a big padding of boundary and a second (split05) with a smaller boundary
  - load each the file with KiCad
  - export dsn file
  - load dsn file with freerouting
  - run autoroute
* [ ] What would you expect freerouting to do in this situation? both files has enough space but the second file with a smaller boundary doesn't finish autorouting
* [ ] Is fixing this issue critical for your work? no, my workaround is to autoroute a file with a bigger boundary and import the Specctra Session
[dsn_files.zip](https://github.com/freerouting/freerouting/files/11779492/dsn_files.zip)

**Comment by andrasfuchs** [comment]
I have just tested this, and I can confirm the issue.

It doesn't make much sense, does it? :)
