### ISSUE TITLE
Need some publicly visible clarification that this is not related to https://freerouting.org/

### ISSUE THREAD

**Issue by rusefi** [freerouting/freerouting#21]
https://freerouting.org/ is totally not related shall we somehow document this?

**Comment by andrasfuchs** [comment]
There is a small chance that the owner of that website could be open to some cooperation, I think. The last time he refreshed his feerouting executable was in 2017, so I think it's worth a shot to contact him, and let him know that we are here, keeping the project alive.

It would be great to have our releases on that URL too.

What do you think, @rusefi?

**Comment by rusefi** [comment]
I've emailed Jürgen on Mar 14, 2020, 10:46 PM and I believe you were CCed?

No response so far.

**Comment by andrasfuchs** [comment]
Yes, you did, sorry! 

Alright then, what would be your recommendation, how would you document this?
