### ISSUE TITLE
[Feature Request]remember last time open design directory and use new open dialog

### ISSUE THREAD

**Issue by EasyEDA2021** [freerouting/freerouting#210]
At present， every time open the design must reload the file path
that is not convenience
suggest remeber last time file path
and suggest use new open file dialog to open file
at present open file dialog:
![image](https://github.com/freerouting/freerouting/assets/29702100/42242373-5d8b-4fe8-8497-7f8ea30a5ee8)

suggest use new dialog
![image](https://github.com/freerouting/freerouting/assets/29702100/1dccb010-4f64-4e10-ab1c-64568e9b985c)

thank you for your time

**Comment by andrasfuchs** [comment]
We have now a saved settings file that remembers the folder that was last used.

This feature will be available in the next release.
