### ISSUE TITLE
freeRouting 1.8.0 goes into a loop trying to route across a keepout, 1.7.0 worked

### ISSUE THREAD

**Issue by retiredfeline** [freerouting/freerouting#217]
To make our work easier, please provide as many details as you can:
* [1.8.0] What version of freerouting are you using?
* [Linux 64-bit] On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?
* [KiCad 7.0.5] What EDA do you use? KiCad, EAGLE, other?
* [DSN] What type of file are you working with? Can you attach the project files (.pro, .kicad_pcb, etc) or the exported DSN file?
* [See below] Did you use any command line arguments?
* [See below] Can you post a screenshot of the problem?
* [] Can you include the latest, related log entries from the .log file?
* [Run the comand on tha attached DSN file] Please list the detailed steps to reproduce the problem
* [Not get into a loop] What would you expect freerouting to do in this situation?
* [No] Is fixing this issue critical for your work?

Command line:

freerouting_jar=/home/data/software/kicad/freerouting-1.8.0-linux-x64/lib/app/freerouting-executable.jar
java -jar $freerouting_jar -mt 1 -dl -de 8088sbc.dsn -do 8088sbc.ses

If the 1.7.0 jar is used, it completes the autorouting and goes on to the optimisation stage.

DSN file and screenshot in zip attached.

[freerouting-issue.zip](https://github.com/freerouting/freerouting/files/12267065/freerouting-issue.zip)

Screenshot separately:

![freerouting-issue](https://github.com/freerouting/freerouting/assets/80862047/620a7410-b3f1-4cc4-8781-a6dcda119da2)

**Comment by andrasfuchs** [comment]
It completed for me after ~210 auto-router passes. It's not ideal, but it works :)
