### ISSUE TITLE
I can't load the .DSN file

### ISSUE THREAD

**Issue by liu2-3zhi** [freerouting/freerouting#222]
To make our work easier, please provide as many details as you can:
* [x] What version of freerouting are you using?

V1.8.0

* [x] On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?

64—bit

* [x] What EDA do you use? KiCad, EAGLE, other?

EasyEDA (https://easyeda.com/)

* [x] What type of file are you working with? Can you attach the project files (.pro, .kicad_pcb, etc) or the exported DSN file?

.DSN

* [X] Did you use any command line arguments?

no parameters

* [x] Can you post a screenshot of the problem?

look down

* [x] Can you include the latest, related log entries from the .log file?

No

* [ ] Please list the detailed steps to reproduce the problem

[Autorouter_PCB13_2023-9-1.zip](https://github.com/freerouting/freerouting/files/12492272/Autorouter_PCB13_2023-9-1.zip)

* [ ] What would you expect freerouting to do in this situation?

I hope it works fine

* [ ] Is fixing this issue critical for your work?

uncertain

WARNING Library.read_scope: app.freerouting.board padstack not found
![image](https://github.com/freerouting/freerouting/assets/43312573/a7a8d820-1cf8-4065-abab-fd07f027a5b3)

![image](https://github.com/freerouting/freerouting/assets/43312573/27683938-5dcb-4475-bb09-d66030e63fe4)

DSN files can be lo

aded normally by konekt electra
![image](https://github.com/freerouting/freerouting/assets/43312573/5c13cd98-7f4c-4a37-92c8-9c1cf780ad6e)

**Comment by liu2-3zhi** [comment]
DSN files can be loaded normally by konekt electra
![image](https://github.com/freerouting/freerouting/assets/43312573/fa6a0911-0bc3-4d34-a0d5-626e2f64b81c)

**Comment by EasyEDA2021** [comment]
please export your PCB design or project file to EasyEDA support, we will have a look
that should be EasyEDA issue, if you use EasyEDA Pro please try latest version, if you use LCEDA Pro, please update to v2.1.33

**Comment by liu2-3zhi** [comment]
I aleady use EasyEDA with the latest version
