### ISSUE TITLE
It doesn't work! this plugin can't finish to route my pcb!

### ISSUE THREAD

**Issue by Betureee** [freerouting/freerouting#225]
I'm using kicad 6.0 on a 2022 MacBook Pro, I created my pcb and when I try to route it, first of all I set all the network classes (0.5mm, 1.0mm, 1.5mm) and when I start the routing works fine, but it stops when 10 components are not connected together, I don't know why, but it's like it feels finished, it works but it's not finished
![ Screenshot 2023-09-19 alle 20 12 42](https://github.com/freerouting/freerouting/assets/134221256/3a39adc3-345b-4f31-94c0-ed0b932f3441) 
![ Screenshot 2023-09-19 alle 20 13 25](https://github.com/freerouting/freerouting/assets/134221256/fffda263-9b85-4657-8848-d9fd82b5c62d)

**Comment by andrasfuchs** [comment]
Thanks for the report @Betureee!

There can be many reasons, so could you answer the following questions:
* What version of freerouting are you using?
* On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?
* What EDA do you use? KiCad, EAGLE, other?
* What type of file are you working with? Can you attach the project files (.pro, .kicad_pcb, etc) or the exported DSN file?
* Did you use any command line arguments?
* Can you post a screenshot of the problem?
* Can you include the latest, related log entries from the .log file?
* Please list the detailed steps to reproduce the problem
* What would you expect freerouting to do in this situation?
* Is fixing this issue critical for your work?

Please also attach KiCad project files if you can.
