### ISSUE TITLE
DSN file did not load properly

### ISSUE THREAD

**Issue by maKhan0811** [freerouting/freerouting#229]
### Please provide as many details as you can
* What version of freerouting are you using?
  ver 1.8

* On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?
  windows 8.1 x64

* What EDA do you use? KiCad, KiCad with freerouting plugin, EAGLE, EasyEDA, other? What is its exact version?
 kicad 4.0.7

* What types of files are you working with? Can you attach the project files (.pro, .kicad_pcb, etc) or the exported DSN file?
 DSN file n kicad pcb file

* Did you use any command line arguments?
no

* Can you post a screenshot of the problem?
yes

* Can you include the latest, related log entries from the .log file?

* Please list the detailed steps to reproduce the problem
when opening the DSN file freeroute the did not properly some pcb modules are missing

* What would you expect freerouting to do in this situation?

* Is fixing this issue critical for your work?
*
![kicad-4 0 7](https://github.com/freerouting/freerouting/assets/146413973/3fd27693-20f3-4be8-8026-ff0867d503c7)

![free-route-1 80](https://github.com/freerouting/freerouting/assets/146413973/4c16fc70-0b71-4dce-bf00-012a372335ee)

[kicad-files.zip](https://github.com/freerouting/freerouting/files/12758419/kicad-files.zip)

**Comment by andrasfuchs** [comment]
It looks like the keepout at the 27. line in the DSN file was exported from KiCad incorrectly. 

Could you please update your KiCad 4.0.7 to [the latest 7.0.8](https://www.kicad.org/) and try again?
