### ISSUE TITLE
java.lang.NoClassDefFoundError: java/net/http/HttpClient

### ISSUE THREAD

**Issue by easyeda2021** [freerouting/freerouting#247]
### Please provide as many details as you can
* What version of freerouting are you using?
v1.9.0
* On what platform did you run it? Windows11,  64-bit

![image](https://github.com/freerouting/freerouting/assets/29702100/09f183a1-6cdb-4010-a935-dd3aa6cd78a8)

when I start the client, it appear this error, I try uninstall and re-install, it still same, anyone can help how to solve this issue?

thanks

**Comment by ProfessorKa0Z** [comment]
I get the same error with 1.9.0 on MacOS 13.5.2 (M1):
<img width="619" alt="image" src="https://github.com/freerouting/freerouting/assets/145606954/1ed37fdb-ee5c-4f8b-80e6-bb01c796f539">
It doesn't seem to affect function though.

**Comment by Nikolai521** [comment]
Same on win7 64 bits
![image](https://github.com/freerouting/freerouting/assets/25958695/69c4b5c6-5b68-43d2-b99f-6971c5d49c6c)

**Comment by SpiderKiCad** [comment]
Same issue. freerouting 1.9.0, Windows 10 x64, jre-8u391-windows-x64 installed:

![freerouting error](https://github.com/freerouting/freerouting/assets/151686690/cd5fd3ec-391f-4576-b134-af05382fd70c)

**Comment by tomthecarrot** [comment]
Same issue on macOS 13.6.2 with OpenJDK 17.

**Comment by andrasfuchs** [comment]
@Lycosaurus That's a great piece of information, I'll take a look when I get to work on the next release. Thanks!

**Comment by jsiddall** [comment]
Also seeing this on V1.9.0 on Linux (since no one else seemed to be running that in the posts I read)

**Comment by codegsaini** [comment]
v1.9.0 same issue on linux 

![Screenshot from 2024-04-16 18-31-24](https://github.com/freerouting/freerouting/assets/77002578/d3cc48c4-f297-438f-bf56-7e4934155972)

**Comment by parasyte** [comment]
It's still a problem. While I hate to add nothing of value with my comment, I don't want to see issues like these closed just because no one is working on them.

**Comment by jsiddall** [comment]
According to issue #288 it is resolved in 2.0

**Comment by parasyte** [comment]
That's good for a future where 2.0 is available.

**Comment by andrasfuchs** [comment]
[Version 2.0 is in the works](https://github.com/freerouting/freerouting/issues/326) and will be released later. You can experiment with [the snapshot build](https://github.com/freerouting/freerouting/releases/tag/SNAPSHOT) until then.

**Comment by fabianlefebre** [comment]
Thanks for the fix!
I am not seeing the issue in the 2.0 snapshot build but I run into a  NoSuchElementException instead when starting the auto router. Could of course be unrelated. (MacOS, java version 21.0.4)

**Comment by andrasfuchs** [comment]
@fabianlefebre It's probably unrelated, but still important. Could you please create a new issue with the details, so that I can fix it before the release? I haven't seen that exception during my tests yet.

**Comment by fabianlefebre** [comment]
@andrasfuchs done! #348
