### ISSUE TITLE
How can I force Freerouting to start again from scratch

### ISSUE THREAD

**Issue by jstrebel** [freerouting/freerouting#254]
Hi, its the first time I use Freerouting (1.9.0)
(I started it via the KiCad GUI Icon) Looking in the DRC I see constraints errors.
After changing the value which forced the error I tried to run the Freerouting again ( by clicking at the GUI Icon)
Problem: I do not see any changes. Freerouting runs a few seconds and exits without a error message.
Q: What is the correct workflow?
Thanks Jakob

Application: KiCad PCB Editor x64 on x64

Version: 7.0.9-109-g0d330051ed, release build

Libraries:
wxWidgets 3.2.4
FreeType 2.12.1
HarfBuzz 8.2.1
FontConfig 2.14.2
libcurl/8.4.0-DEV Schannel zlib/1.3

Platform: Windows 10 (build 19045), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
Date: Dec 11 2023 04:13:46
wxWidgets: 3.2.4 (wchar_t,wx containers)
Boost: 1.83.0
OCC: 7.7.1
Curl: 8.4.0-DEV
ngspice: 41
Compiler: Visual C++ 1936 without C++ ABI

Build settings:
KICAD_SPICE=ON

**Comment by andrasfuchs** [comment]
I'm not sure if you mean this, but we have a "Delete all tracks and vias" function in the "Other" menu.
![image](https://github.com/freerouting/freerouting/assets/910321/e418103b-f59d-42e0-93cc-94a382e389a5)

This will remove all routed paths and you can start the routing process over.
