### ISSUE TITLE
Reducable 20 seconds timeout of first dialog

### ISSUE THREAD

**Issue by chatelao** [freerouting/freerouting#266]
### Please provide as many details as you can
* What version of freerouting are you using? 1.9.0
* On what platform did you run it? Windows, 64
* What EDA do you use? KiCad with freerouting plugin
* Did you use any command line arguments? No

### IS
- At startup the plug-in shows the 20 second dialog.

### WOULD LIKE
- I would like to start immediatly every time.

**Comment by andrasfuchs** [comment]
You can use the `-dct` command line argument to change the timeout:
`-dct [seconds]: dialog confirmation timeout. Sets the timeout of the dialogs that start a default action in x seconds. 20 seconds by default.`

If you can't for some reason then you can still edit the `freerotuing.json` file in your `temp` folder:
![image](https://github.com/freerouting/freerouting/assets/910321/38fe4cfc-f530-4e67-bd05-af952fc15585)
