### ISSUE TITLE
Do profiling and performance optimization

### ISSUE THREAD

**Issue by andrasfuchs** [freerouting/freerouting#271]
Thanks to @chatelao, I discovered a great tool, [VisualVM](https://visualvm.github.io/) that makes it possible to measure the performance of any Java app.

I already did some testing and there is a chance that there is room for improvement in our routing algorithm.

It's probably worth spending a day or two on this to achieve some speedup. 
@chatelao might be able to help me with GPU acceleration as well ;)

![image (1)](https://github.com/freerouting/freerouting/assets/910321/ff7ea646-90d2-4788-ac34-a239a00f0626)

![image (2)](https://github.com/freerouting/freerouting/assets/910321/19d6e042-796b-47fd-8982-cb55504ac56e)

**Comment by andrasfuchs** [comment]
I disable multithreading and I start benchmarking with the following parameters:
`-de .\tests\Issue102-Mars-64-revE-rot00.dsn -do .\tests\Issue102-Mars-64-revE-rot00.ses`

The baseline is on my machine is:
* Auto-routing: 34.63 seconds
* Route optimization: 5 minutes 45.11 seconds

**Comment by andrasfuchs** [comment]
The route optimizer creates a ton of new objects that are only used temporarily. I wonder if we could recycle those objects?

![image](https://github.com/freerouting/freerouting/assets/910321/7d411283-f2be-46dc-9662-27f9695c3355)

**Comment by andrasfuchs** [comment]
After a few hours of code optimization I got the following results:

* Auto-routing: 29.34 seconds
* Route optimization: 2 minutes 40.10 seconds (128 -> 116 vias, 3.908 -> 3.769 mm of wires)

Auto-routing sped up 18%, route optimization got nearly twice as fast, at the cost of 4 more vias than with the previous settings.

There are still opportunities here, but that will do for now.

**Comment by chatelao** [comment]
Sounds great, thanks for mentioning.
