### ISSUE TITLE
Dont route nets connections that are already connected with copper

### ISSUE THREAD

**Issue by savio-code** [freerouting/freerouting#292]
The program should automatically skip connections that are already connected with copper, right now it still tries to route traces that already have connection with copper 

![Capture](https://github.com/freerouting/freerouting/assets/11610818/c4814de5-04ec-4a36-95bf-6a3a41804c56)

**Comment by andrew64k** [comment]
This would be great....But, what if the ground between two pads is very far away? I think that would cause some issues in some cases.
