### ISSUE TITLE
No response during setup 

### ISSUE THREAD

**Issue by cuu123** [freerouting/freerouting#293]
No response during setup 
I tried several times on this laptop. 
Please help!
![pic](https://github.com/freerouting/freerouting/assets/40519958/bf1adcc0-b9ce-4998-9082-cde22e791b91)

### Please provide as many details as you can
* What version of freerouting are you using?
freerouting-1.9.0-windows-x64

* On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?
Win10 64-bit
 
* What EDA do you use? KiCad, KiCad with freerouting plugin, EAGLE, EasyEDA, other? What is its exact version?

* What types of files are you working with? Can you attach the project files (.pro, .kicad_pcb, etc) or the exported DSN file?

* Did you use any command line arguments?

* Can you post a screenshot of the problem?

* Can you include the latest, related log entries from the .log file?

* Please list the detailed steps to reproduce the problem

* What would you expect freerouting to do in this situation?

* Is fixing this issue critical for your work?

**Comment by andrasfuchs** [comment]
@cuu123 Sorry, but that's not enough information.

Have you tried another computer? Can you replicate the problem there as well?

How is your CPU usage at this point? Do you have any logs recorded by the installer?

**Comment by cuu123** [comment]
Have you tried another computer? Yes, it works on my PC with AMD Ryzen 2400

Can you replicate the problem there as well? however, still not working on my laptop (i5 6300HQ CPU)

How is your CPU usage at this point? Normal around 60% for average  

Do you have any logs recorded by the installer? How to check the logs?

**Comment by cuu123** [comment]
=== Logging started: 2024/4/4  7:06:42 ===
Action 7:06:42: INSTALL. 
Action start 7:06:42: INSTALL.
Action 7:06:42: FindRelatedProducts. Searching for related applications
Action start 7:06:42: FindRelatedProducts.
Action ended 7:06:42: FindRelatedProducts. Return value 1.
Action 7:06:42: PrepareDlg. 
Action start 7:06:42: PrepareDlg.
Info 2898.For WixUI_Font_Normal textstyle, the system created a 'Tahoma' font, in 0 character set, of 16 pixels height.
Info 2898.For WixUI_Font_Bigger textstyle, the system created a 'Tahoma' font, in 0 character set, of 24 pixels height.
Action 7:06:42: PrepareDlg. Dialog created
Action ended 7:06:42: PrepareDlg. Return value 1.
Action 7:06:42: AppSearch. Searching for installed applications
Action start 7:06:42: AppSearch.
AppSearch: Property: RM_RF48431AECBD69377EA800D62616352F20, Signature: regsearch44413c41962833c69ffb8268f3119343
Action ended 7:06:42: AppSearch. Return value 1.
Action 7:06:42: ValidateProductID. 
Action start 7:06:42: ValidateProductID.
Action ended 7:06:42: ValidateProductID. Return value 1.
Action 7:06:42: CostInitialize. Computing space requirements
Action start 7:06:42: CostInitialize.
Action ended 7:06:42: CostInitialize. Return value 1.
Action 7:06:42: FileCost. Computing space requirements
Action start 7:06:42: FileCost.
Action ended 7:06:42: FileCost. Return value 1.
Action 7:06:42: CostFinalize. Computing space requirements
Action start 7:06:42: CostFinalize.
Action ended 7:06:42: CostFinalize. Return value 1.
Action 7:06:42: MigrateFeatureStates. Migrating feature states from related applications
Action start 7:06:42: MigrateFeatureStates.
Action ended 7:06:42: MigrateFeatureStates. Return value 0.
Action 7:06:42: WelcomeEulaDlg. 
Action start 7:06:42: WelcomeEulaDlg.
Info 2898.For WixUI_Font_Title textstyle, the system created a 'Tahoma' font, in 0 character set, of 18 pixels height.
Action 7:06:42: WelcomeEulaDlg. Dialog created
Action ended 7:06:44: WelcomeEulaDlg. Return value 1.
Action 7:06:44: ProgressDlg. 
Action start 7:06:44: ProgressDlg.
Action 7:06:44: ProgressDlg. Dialog created
Action ended 7:06:44: ProgressDlg. Return value 1.
Action 7:06:44: ExecuteAction. 
Action start 7:06:44: ExecuteAction.
Action 7:07:15: CancelDlg. Dialog created

**Comment by andrasfuchs** [comment]
As far as I can tell we can't control the exact actions that are executed in the installer, and your installer failed somewhere at "Action start 7:06:44: ExecuteAction.". 

I have no experience with the installer configuration, but you can try some settings in our MSI creation batch file '[create-distribution-windows-x64.bat](https://github.com/freerouting/freerouting/blob/master/distribution/create-distribution-windows-x64.bat)'.

**Comment by L1uTongweiNewAccount** [comment]
>![snapshot error](https://private-user-images.githubusercontent.com/40519958/324662414-efb9b16f-2e17-4532-b203-ee9522269a1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTc2ODAsIm5iZiI6MTcxODE1NzM4MCwicGF0aCI6Ii80MDUxOTk1OC8zMjQ2NjI0MTQtZWZiOWIxNmYtMmUxNy00NTMyLWIyMDMtZWU5NTIyMjY5YTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAxNTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ZTI5OWIzOTdkNWQ1ODRjNTI3ZDg5ODg5MjI2OTVlMjFlYjdjNDJmNjcwODhiNzJiYjY0OGUwNzhmOWVhZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eVX9JdbhpjE6YCf2FLcI0eEH071GdQewpiKOIMhI7rY)

See issue #247 in this warning.

Check your OS for no respomse, I think it's not a issue for freerouting.
