### ISSUE TITLE
KiCAD Package Manager URL ERROR

### ISSUE THREAD

**Issue by zly20129** [freerouting/freerouting#295]
### Please provide as many details as you can
* What version of freerouting are you using?
1.9.0
* On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?
Win10 X64
* What EDA do you use? KiCad, KiCad with freerouting plugin, EAGLE, EasyEDA, other? What is its exact version?
KiCad
* What types of files are you working with? Can you attach the project files (.pro, .kicad_pcb, etc) or the exported DSN file? (Please note that GitHub doesn't allow DSN file uploads, so you need to ZIP it before uploading.)
NULL
* Did you use any command line arguments?
NULL
* Can you post a screenshot of the problem?

Please refer to https://gitlab.com/kicad/services/kicad-plugins/-/issues/1

* Can you include the latest, related log entries from the .log file?
NULL
* Please list the detailed steps to reproduce the problem

- There is no folder named RAW. https://github.com/freerouting/freerouting/raw/master........Omitted later

- Actual website address: https://github.com/freerouting/freerouting/tree/master/integrations/KiCad

* What would you expect freerouting to do in this situation?
Fix URL.
* Is fixing this issue critical for your work?
No.

**Comment by andrasfuchs** [comment]
The discussion will be continued [on KiCad GitLab](https://gitlab.com/kicad/services/kicad-plugins/-/issues/1).
