### ISSUE TITLE
Feature request: fully batched routing

### ISSUE THREAD

**Issue by freerouting** [freerouting/freerouting#3]
It should be possible to autoroute a board without launching any GUI.

Implementation problem: currently the processing code is too coupled with GUI code, see class BoardHandling. Refactoring would be needed in order to decouple processing from GUI.

**Comment by BenF1000** [comment]
I have been playing with the freerouting script for a project which I am working on and I am very impressed! It would be great to have this feature however (where the autorouter can be launched from the commandline) - I noticed a couple of commits related to 'headless' operation and decoupling the logic from the UI, but I cant figure out whether this feature has been implemented yet or not? Please could you confirm, and if so let me know how it would be used from the commandline ?

**Comment by andrasfuchs** [comment]
I have implemented a few extra command line arguments that make it possible to use freerouter with scripts. It still launches the GUI, but it automatically does the auto-routing for a number of passes and saves the results into a file and exits the app.

Check out the end of the README in this repo: https://github.com/miho/freerouting
