### ISSUE TITLE
Exporting routing files in the .rte format

### ISSUE THREAD

**Issue by Raintimewang** [freerouting/freerouting#310]
### Please provide as many details as you can
* What version of freerouting are you using?
I am currently using the latest stable version of Freerouting.
* On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?
I am running Freerouting on a 64-bit Windows platform.
* What EDA do you use? KiCad, KiCad with freerouting plugin, EAGLE, EasyEDA, other? What is its exact version?
I am using Altium Designer. Unfortunately, Altium Designer does not natively support Freerouting directly. 
* What types of files are you working with? Can you attach the project files (.pro, .kicad_pcb, etc) or the exported DSN file? (Please note that GitHub doesn't allow DSN file uploads, so you need to ZIP it before uploading.)
I primarily work with Altium Designer project files, including .PrjPCB, .SchDoc, and .PcbDoc. Additionally, I use exported DSN files for routing.
* Did you use any command line arguments?
No specific command line arguments were used during my process.
* What would you expect freerouting to do in this situation?
I am hoping for support in exporting routing files in the .rte format from Altium Designer. This would greatly enhance my workflow and compatibility with other tools.
* Is fixing this issue critical for your work?
* yes

**Comment by L1uTongweiNewAccount** [comment]
EasyEDA supports import Altium Designer design, so you can import your design in EasyEDA first, then export .dsn in EasyEDA.

EasyEDA supports offline mode so you don't need to register a account and upload your design in server.
