### ISSUE TITLE
Autorouting never finishes with kicad

### ISSUE THREAD

**Issue by dpalic** [freerouting/freerouting#321]
### Please provide as many details as you can
* What version of freerouting are you using?
1.9.0 via kicad

* On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?
Linux and Windows both x64

* What EDA do you use? KiCad, KiCad with freerouting plugin, EAGLE, EasyEDA, other? What is its exact version?
KiCAD 8.0.3

* What types of files are you working with? Can you attach the project files (.pro, .kicad_pcb, etc) or the exported DSN file? (Please note that GitHub doesn't allow DSN file uploads, so you need to ZIP it before uploading.)

I can provide the project file privately, but not here in public

* Did you use any command line arguments?
no, but tried to toggle with fanout (disabled by default) and disabling optimize. Both did not help

* Can you post a screenshot of the problem?
not relevant, you only see over 5000 iterations. The 5000 iterations, have been 3 days on consecutive autorouting.
The issue is also that the CPU is not utilized well. Having a 16core machine, mostly 1-2 cores are even used during autorouting. During start it is seldomly more than 3 cores.

* Can you include the latest, related log entries from the .log file?
if you tell me how to enable logging, i can do so

* Please list the detailed steps to reproduce the problem
we have a medium complex board, which requires a autorouting. Sadly the autoreouting is simply never ending

* What would you expect freerouting to do in this situation?
to have a successful termination of the autorouting

* Is fixing this issue critical for your work?
yes, since autorouting is not usable at all

**Comment by andrasfuchs** [comment]
Could you try to use our latest snapshot build?

First, you need to download the most recent .jar version from here: 
https://github.com/freerouting/freerouting/releases/tag/SNAPSHOT

Then, you will need to replace your installed freerouting.jar file with the snapshot one in your KiCad plugins folder.

Please try the routing again. There were some changes made already since version 1.9 that might solve this issue.
