### ISSUE TITLE
unconnected islands in fill zones

### ISSUE THREAD

**Issue by GorillaSapiens** [freerouting/freerouting#356]
kicad 8.0.5, freerouting plugin 1.9.0

freerouting literally leaves unconnected islands in fill zones that could be easily connect.

given this and other bugs, i cannot reasonably expect that FreeRouting's solution is correct.

i'm back to hand routing this board.  DEEPLY disappointed.

![untrustworthy](https://github.com/user-attachments/assets/b8802196-d883-4af7-acbd-2cdaa2262228)

**Comment by GorillaSapiens** [comment]
![fuckingworthless](https://github.com/user-attachments/assets/a2d6a8ab-d867-416c-8b52-82849c2b433f)

**Comment by GorillaSapiens** [comment]
this has more to do with fill settings in kicad.  this isn't a freerouting bug.  sorry.  closing.

**Comment by andrasfuchs** [comment]
No worries, thank you for letting me know!
