### ISSUE TITLE
Connections not found

### ISSUE THREAD

**Issue by golkit1** [freerouting/freerouting#375]
I'm using Macos 14.5 M1 pro. 
I downloaded v2.0 and run it on a board I made.
I get this error:
Autoroute complete. 208 connection not found. 
What it can be?
<img width="1090" alt="Screenshot 2024-11-11 at 15 51 04" src="https://github.com/user-attachments/assets/96781595-26c6-4dd3-8085-cc4436c9b528">

**Comment by andrew64k** [comment]
I see the same problem after the optimization finished. It says a large number of connections not found.
Most of the time it did complete all of the connections. Sometimes it does not, but only a few are left unconnected.

**Comment by andrasfuchs** [comment]
Thanks @golkit1 for the report, and @andrew64k for the reaction!
That was a small carelessness on my part, it should display the correct number now. You will see the changes in the next release.

**Comment by andrew64k** [comment]
It's better now. But the autoroute now seems to fail on the last few connections but starts the optimizer anyway (if selected). Before it was finding all the connections and reported the vias before starting the optimizer.
