### ISSUE TITLE
short traces

### ISSUE THREAD

**Issue by freerouting** [freerouting/freerouting#4]
I was not able to reroute a board that has been previously routed by FreeRouter because it seems to leave a lot of zero-length traces laying around that cause the FreeRouter to be unable to load the DSN file.  So if I needed to reroute a board, I always had to remove all the traces and start again from scratch or revert to pre-autorouted version of the board.

**Comment by andrasfuchs** [comment]
As @abelom mentioned, this issue is probably related to #15.

Since the user @ghost got deleted, we have no way to prove or disprove that the fix would work for their case. 

I close this.
