### ISSUE TITLE
Question/Feature: Script for deeper EAGLE integration

### ISSUE THREAD

**Issue by ranseyer** [freerouting/freerouting#43]
When i use Freeroute, i have alway the same workflow
-remove the GND Polygons
-Run the ULP for creating the DSN File
-undo the removal of the GND Polygon
-Open Freeroouter
-Search the ULP / start the autorouting
-Save the EAGLE-Script
-Run the script in EAGLE

I have not really experiance with EAGLE scripts. But i tsounds for me much easier only run a script for all of this (except of the GND Polygons thing...):

The EAGLE script could:
- run the ULP which creates the DSN File
- run freerouter with command-line parameters to the ULP file
- maybe runs the created session-script directly in EAGLE

Does somebody know if such an script exists ?

* [ ] What version of freerouting are you using? 1.4.4
* [ ] On what platform did you run it? Windows 64-bit

**Comment by andrasfuchs** [comment]
An updated Eagle ULP script is now available in [Integrations\Eagle](https://github.com/freerouting/freerouting/tree/master/integrations/Eagle). I'm sure if it satisfies your original request though.

I close this issue now, but let me know if you think it should be better in some way.
