### ISSUE TITLE
Error Message When Installing on OSX Mojave 10.14.6

### ISSUE THREAD

**Issue by hhaudio** [freerouting/freerouting#49]
Hi, I am trying to install Freerouting on OSX Mojave 10.14.6 for use with KiCad (5.1.2). I downloaded the installer from the following source: https://github.com/freerouting/freerouting/releases/tag/v1.4.4

When I open the downloaded dmg I get a folder with the freerouting program inside. When I try to open this program I get an error message saying that it's "damaged and can't be opened" (see attached image). Same thing happens when I try moving the application elsewhere on my computer.  

<img width="537" alt="FreeRouting_Error" src="https://user-images.githubusercontent.com/37379609/117460049-10c09880-af1a-11eb-87b8-cd7ca43b1d87.png">

Anything you can think of that might be causing this? I am currently working on a board with several hundred low hz signals to route and this option would be much preferable to doing it by hand. Thanks!

**Comment by andrasfuchs** [comment]
This might be a similar to the issue #30.

I'm not familiar with OSX, but @pierremolinaro's solution might work for you too:
`sudo xattr -cr <<path>>/Freerouting.app`

**Comment by hhaudio** [comment]
@andrasfuchs This worked for me, thanks! Perhaps worth making a note of on the downloads page.

**Comment by andrasfuchs** [comment]
I'm glad it worked!

Is your project publicly accessible? Judging by the "several hundred low hz signals" expression it must be a really interesting piece of hardware ;)

**Comment by hhaudio** [comment]
@andrasfuchs Not publicly accessible as of yet, but will be online once it's finished. It's for a piece of PCB artwork in this vein: https://www.hammerheadaudio.com/art/great-wurm https://www.hammerheadaudio.com/art/knave-death
