### ISSUE TITLE
binary not available for download

### ISSUE THREAD

**Issue by Corallus-Caninus** [freerouting/freerouting#50]
I am unable to download the binary from the website and get a 403 response.

Thanks.

**Comment by andrasfuchs** [comment]
Did you try to download them from https://github.com/freerouting/freerouting/releases/?

It seems to be working for me at the moment. Could you try it again?

**Comment by miho** [comment]
I think this is related to the recent bintray shutdown. I will fix it asap. Meanwhile use the link mentioned by @andrasfuchs .

**Comment by miho** [comment]
We link to Github now.
