### ISSUE TITLE
New multithreading causes softlock

### ISSUE THREAD

**Issue by WasdeAsde** [freerouting/freerouting#73]
* [v1.4.5] What version of freerouting are you using?
* [Windows 64bit] On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?
   Intel i5-6200U CPU @ 2.30GHz, 2 cores, 4 threads
   16gb DDR4
* [DSN, sadly no] What type of file are you working with? Can you attach the actual (DSN) file?
* [none] Did you use any command line arguments?
* [no] Can you post a screenshot of the problem?
* [no] Can you include the latest, related log entries from the .log file?
* [] Please list the detailed steps to reproduce the problem
     launch with start menu, shortcut, cmd without any arguments
     open .dsn and start autorouting
* [] What would you expect freerouting to do in this situation?
      add automatic thread detection
      add thread-limit based on system thread count
      and/or add option to GUI for multithreading adjustment
* [no] Is fixing this issue critical for your work?

Additional information:
Multithreading is quite helpful, but in the default setting (-mt 32) it can overload some computers. More jobs are submitted than can be handled. The result is a softlock of the system. Could provoke the error several times on my computer and on an even older Ubuntu system (from ca 2013). 

Hotfix: After specifying the argument "-mt 4" (matching my system) 100% CPU utilization but without softlock. 

However, an automatic maximum thread limit based on the system's thread count would be helpful for the future, similar to nproc on Linux.

**Comment by miho** [comment]
The Java runtimes often uses `#threads= #cores - 1` as default thread pool size if it detects multiple cores. 

Note to developers: you can check this via

```java
int numOfCores      = Runtime.getRuntime().availableProcessors();
int commonPoolSize  = ForkJoinPool.commonPool().getParallelism();
```

For CPU-bound tasks I would use the same conservative formula.

P.S.: sorry for my long absence. But from what I can see, freerouting is doing well.
